"""movie_list

Revision ID: 2103ba0c833a
Revises: 6e01e404ab07
Create Date: 2023-12-30 23:03:18.802066

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2103ba0c833a"
down_revision: Union[str, None] = "6e01e404ab07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movielist", "movie_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("movielist", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movielist", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("movielist", "movie_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
