"""uuid

Revision ID: 6e01e404ab07
Revises: 4e4bbaf5d014
Create Date: 2023-12-23 00:49:28.086069

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e01e404ab07"
down_revision: Union[str, None] = "4e4bbaf5d014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category", ["id"])
    op.create_unique_constraint(None, "movie", ["id"])
    op.create_unique_constraint(None, "movielist", ["id"])
    op.create_unique_constraint(None, "rate", ["id"])
    op.create_unique_constraint(None, "review", ["id"])
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "review", type_="unique")
    op.drop_constraint(None, "rate", type_="unique")
    op.drop_constraint(None, "movielist", type_="unique")
    op.drop_constraint(None, "movie", type_="unique")
    op.drop_constraint(None, "category", type_="unique")
    # ### end Alembic commands ###
